#!/data/busybox/sh

BYTE_1=$1
BYTE_2=$2
BYTE_3=$3

NUM_OF_ARGS=$#

if [ $NUM_OF_ARGS != 3 ]; then
echo "Error! , Only 3 arguments (bytes) are required - The first 3 bytes 08-00-28 are reserved for TI MAC Address "
echo "i.e. by running ./edit_nvs_mac_address 12 34 56 the new MAC will be set to 08-00-28-12-34-56"
exit
fi


if [ ${#BYTE_1} != 2 ]; then
echo "Error! , Each argument (byte) should be 2 chars long in Hex format!"
echo "i.e. 0x8C should be written as 8C"
exit
fi

if [ -f nvs_map.bin ]; then
echo "Updating nvs_map.bin Mac Address..."
else
"Error! , nvs_map.bin file not found!!!"
exit
fi


cp nvs_map.bin nvs_test
cp nvs_map.bin nvs_map.bin.latest
echo -en \\x$BYTE_3\\x$BYTE_2\\x$BYTE_1 > number
dd if=number of=nvs_test obs=1 conv=notrunc seek=3

cp nvs_test nvs_map.bin
rm number
rm nvs_test

sync
echo "Your new MAC Address is: 08-00-28-$BYTE_1-$BYTE_2-$BYTE_3 ."

